name: AWS S3 List

on:
  push:
    branches:
      - main

jobs:
  s3_list:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      
      - name: List S3 bucket contents
        run: aws s3 ls
