name: AWS S3 List

on:
  push:
    branches:
      - main

jobs:
  aws-s3-list:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
  
      - name: List objects in S3 bucket
        run: aws s3 ls 
